[theme]
primaryColor             = "#0369a1"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f0f9ff"
textColor                = "#0f172a"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
